### ISSUE TITLE
css and js not loading on prod

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#153]
Some of css and js does not load on prod.
As @alexandru-m-g helped me, the headers are off (missing `Content-Encoding`, lots of `Pragma` headers, missing `Via-Varnish` header).
The content of those js/css files seem gzipped (as Joe T. suggested) but the browser does not interpret those as gzipped files.

**Comment by teodorescuserban** [comment]
Fixed.
After ruling out ckan itself, files on ckan side, nginx cache and nginx config, I have restarted the varnish container.
Issue persisted.
I stopped the Varnish container, removed it and recreating it. Problem solved.

**Comment by amcguire62** [comment]
Serban can i check since when the problem occurred and do we know why and what do we do to make sure does not happen again. I am guessing we would not have noticed but for the fact that Andrej happened to open and tell us. So need to be careful with this one as we were a bit blindsided because initially we could not see it.

**Comment by teodorescuserban** [comment]
The cause seems to be the varnish container inconsistency.
A re-creation of the container resolved the issue.
Same thing happened on hr.info only they got down really hard.
As I intend to remove varnish from our stack really soon, I would leave this as it is.

**Comment by amcguire62** [comment]
Serban can i check since when the problem
