### ISSUE TITLE
Set up automated monitoring for CKAN and CPS

### ISSUE THREAD

**Issue by amcguire62** [OCHA-DAP/hdx-infrastructure#32]
We need a way to monitor the performance of all servers (webpage ideally / perhaps linked to pingdom) so anyone can see what is server status (this can be used by communications team to keep users informed of downtime / issues for example)

**Comment by teodorescuserban** [comment]
Working on a monitoring system based on icinga (http://www.icinga.com) and munin (http://munin-monitoring.org

Will ping you when the site is available, @amcguire62

**Comment by teodorescuserban** [comment]
Monitoring server online.
I informed @amcguire62 and @davidmegginson and made them accounts on it.
TO DO: install monitoring agents on our VMs and make them communicate the status of various parameters to our monitoring host (we need to do passive checks).
When agents are connected to our monitoring host, I will ping you both to suggest parameters to monitor, because sky's the limit here :)

**Comment by cjhendrix** [comment]
@amcguire62 @teodorescuserban After our hardware failure a few weeks ago, I believe we decided to set up Pingdom as an additional monitoring system.  Any progress on that?

**Comment by teodorescuserban** [comment]
I talked with @amcguire62 and will create the account and enable tests as late as tomorrow cob.
